; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32_s3_n8r8
framework = arduino
platform_packages = tool-mklittlefs@file://./local_packages/tool-mklittlefs
debug_tool = esp-builtin
debug_load_mode = manual
debug_init_break = tbreak setup
board_build.f_cpu = 240000000L
upload_protocol = esptool
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
debug_speed = 12000
build_type = debug
extra_scripts = pre:select_elegantota.py, merge-bin.py, set_mklittlefs.py
board_build.filesystem = littlefs
lib_deps = 
	adafruit/Adafruit GFX Library@^1.11.3
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit seesaw Library @ ^1.6.3
	adafruit/Adafruit SSD1306 @ ^2.5.7
	adafruit/Adafruit BusIO @ ^1.14.1
	adafruit/Adafruit BNO055 @ ^1.6.1
	adafruit/Adafruit Unified Sensor @ ^1.1.7
	kosme/arduinoFFT@^1.5.6
	.\lib\ElegantOTAPro-3-1-4
	ESP32Async/AsyncTCP@^3.3.2
	ESP32Async/ESPAsyncWebServer@^3.9.3
	bblanchon/ArduinoJson@^6.21.5
	adafruit/Adafruit NeoPixel @ ^1.12.4
	https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
	ricmoo/QRCode @ ^0.0.1
	sparkfun/SparkFun APDS9960 RGB and Gesture Sensor @ ^1.4.3
	https://github.com/ayushsharma82/ElegantOTA.git
	https://github.com/BaiTian6641/RevEng_PAJ7620.git
	https://github.com/m5stack/M5GFX.git
	https://github.com/m5stack/M5Unified.git
	https://github.com/ayushsharma82/NetWizard.git
build_flags = 
	-g -Og
	-D TASESP32S3
	-D BOARD_HAS_PSRAM
	-D CONFIG_SPIRAM_USE=SPIRAM_USE_MALLOC
	-D CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP
	-D CONFIG_SPIRAM_XIP_FROM_PSRAM
	-D CONFIG_SPIRAM_MEMTEST
	-D CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY
	-D CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY
	-D CONFIG_SPIRAM_FETCH_INSTRUCTIONS
	-D CONFIG_SPIRAM_RODATA
	-D CONFIG_SPIRAM_SPEED_120M
	-D CONFIG_SPIRAM_BOOT_INIT
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USE_PSRAM_FOR_FACE_JSON
	-D NETWIZARD_USE_ASYNC_WEBSERVER=1
	-D OTA_BTN=14
	-D CONFIG_IDF_TARGET_ESP32S3
	-D CONFIG_SPIRAM_ECC_ENABLE
	-O3

[env:esp32p4]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-p4-evboard
framework = arduino
platform_packages = tool-mklittlefs@file://./local_packages/tool-mklittlefs
upload_protocol = esptool
monitor_speed = 115200
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
build_type = debug
extra_scripts = pre:select_elegantota.py
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	-D CONFIG_SPIRAM_USE=SPIRAM_USE_MALLOC
	-D TASESP32P4
	-D CONFIG_IDF_TARGET_ESP32P4
	-D BOARD_HAS_PSRAM
	-D CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP
	-D CONFIG_SPIRAM_XIP_FROM_PSRAM
	-D CONFIG_SPIRAM_MEMTEST
	-D CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY
	-D CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY
	-D CONFIG_SPIRAM_FETCH_INSTRUCTIONS
	-D CONFIG_SPIRAM_RODATA
	-D CONFIG_SPIRAM_BOOT_INIT
	-D CONFIG_SPIRAM_ECC_ENABLE
	-D OTA_BTN=25
	-D USE_PSRAM_FOR_FACE_JSON
	-D NETWIZARD_USE_ASYNC_WEBSERVER=1
	-O3
	-D CORE_DEBUG_LEVEL=0
lib_deps = 
	adafruit/Adafruit GFX Library@^1.11.3
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit seesaw Library @ ^1.6.3
	adafruit/Adafruit SSD1306 @ ^2.5.7
	adafruit/Adafruit BusIO @ ^1.14.1
	adafruit/Adafruit BNO055 @ ^1.6.1
	adafruit/Adafruit Unified Sensor @ ^1.1.7
	kosme/arduinoFFT@^1.5.6
	.\lib\ElegantOTAPro-3-1-4
	ESP32Async/AsyncTCP@^3.3.2
	ESP32Async/ESPAsyncWebServer@^3.9.3
	bblanchon/ArduinoJson@^6.21.5
	adafruit/Adafruit NeoPixel @ ^1.12.4
	ricmoo/QRCode @ ^0.0.1
	sparkfun/SparkFun APDS9960 RGB and Gesture Sensor @ ^1.4.3
	https://github.com/ayushsharma82/ElegantOTA.git
	https://github.com/BaiTian6641/RevEng_PAJ7620.git
	https://github.com/m5stack/M5GFX.git
	https://github.com/m5stack/M5Unified.git
	https://github.com/ayushsharma82/NetWizard.git

[platformio]
description = This project is a 3D ray-tracing and animation engine for pixel matrices, designed to be used for drawing live animations on Protogen style characters from 3D object files (.OBJ).
